name = "GMTF3D"
uuid = "fdccb625-bdcb-4ada-a16d-8b3036ea332b"
authors = ["Joaquim <jluis@ualg.pt> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
